name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests as well

jobs:
  build:
    runs-on: ubuntu-latest # Use an Ubuntu machine to run the tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Checkout code from the repo

    - name: Set up Python
      uses: actions/setup-python@v2 # Set up Python environment
      with:
        python-version: '3.10.11' 
        
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt 
        pip install flake8  # Ensure flake8 is installed

    - name: Verify installation of flake8
      run: |
        source venv/bin/activate
        pip list  # List installed packages to verify flake8 is installed
    
    - name: Lint with flake8
      run: |
        source venv/bin/activate
        flake8 --exclude=venv,my-venv --ignore=E501 --count --show-source --statistics    # exclude virtual environment packages from linting and ignore line too long error E501

    - name: Run Tests 
      run: |
        source venv/bin/activate
        pytest 
