name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests as well

jobs:
  build:
    runs-on: ubuntu-latest # Use an Ubuntu machine to run the tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Checkout code from the repo

    - name: Set up Python
      uses: actions/setup-python@v2 # Set up Python environment
      with:
        python-version: '3.10.11' 
        
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt 

    - name: Run Tests 
      run: |
        source venv/bin/activate
        pytest 
