name: Ping Website Every 15 Minutes

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping website
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://mapmorph-mcp140.pythonanywhere.com/
